Repository FundingCircle/shipment_tracker, pull requests merged in 2019-02, with the labels that each got.

#377 Prevent unnecessary repo re-clone caused by concurrent fetches
  .circleci/config.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/git_repository_loader.rb
  spec/models/git_repository_loader_spec.rb
Labels: bug, enhancement

#389 Gem updates
  Gemfile.lock
Labels: Security

#385 Add a Delayed Job web interface
  Gemfile
  Gemfile.lock
  config/initializers/delayed_job.rb
  config/initializers/omniauth.rb
  config/routes.rb
Labels: enhancement
