Repository FundingCircle/shipment_tracker, pull requests merged in 2019-09, with the labels that each got.

#423 Retry commit status updates when GitHub API rate limit is reset
  .circleci/config.yml
  Dockerfile
  Gemfile.lock
  app/jobs/commit_status_error_job.rb
  app/jobs/commit_status_not_found_job.rb
  app/jobs/commit_status_reset_job.rb
  app/jobs/commit_status_retryable_job.rb
  app/jobs/commit_status_update_job.rb
  app/jobs/relink_ticket_job.rb
  app/use_cases/handle_push_event.rb
  config/initializers/delayed_job.rb
  lib/clients/github.rb
  spec/jobs/commit_status_error_job_spec.rb
  spec/jobs/commit_status_not_found_job_spec.rb
  spec/jobs/commit_status_reset_job_spec.rb
  spec/lib/clients/github_spec.rb
Labels: bug, enhancement

#424 Allow disabling github status updates for certain applications
  app/models/commit_status.rb
  config/application.rb
  spec/models/commit_status_spec.rb
Labels: enhancement

#428 Stop git fetch in RelinkTicketJob
  app/jobs/relink_ticket_job.rb
  config/application.rb
Labels: bug

#421 Auto link a ticket on PR to master only
  app/jobs/auto_link_ticket_job.rb
  app/models/payloads/github_pull_request.rb
  app/use_cases/handle_pull_request_created_event.rb
  spec/jobs/auto_link_ticket_job_spec.rb
  spec/models/payloads/github_pull_request_spec.rb
  spec/use_cases/handle_pull_request_created_event_spec.rb
Labels: enhancement
